ALTER TABLE copy_trading
    MODIFY COLUMN copy_mode VARCHAR(32) NOT NULL DEFAULT 'RATIO'
        COMMENT '跟单金额模式（RATIO/FIXED/PROPORTIONAL_RISK）';

ALTER TABLE copy_trading_templates
    MODIFY COLUMN copy_mode VARCHAR(32) NOT NULL DEFAULT 'RATIO'
        COMMENT '跟单金额模式（RATIO/FIXED/PROPORTIONAL_RISK）';
